name: Flutter Release Build

on:
  push:
    branches:
      - main
      # Add tags to trigger release build only on tag push
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Release APK
      run: flutter build apk --release

    - name: Show Contents of build directory
      run: ls -R build

    - name: Archive Release APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk
